apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    last: final
    author: farhod
  name: nginx2
  namespace: farhod
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
