apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-pod
  name: busybox-pod
  namespace: farhod
spec:
  containers:
  - args:
    - echo
    - "THE BEST DEVOPS COURCE"
    image: busybox
    name: busybox-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
